/run/numberOfThreads 1

# Initialize kernel
/run/initialize

/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/gun/particle neutron
/gun/energy 0.1 eV
/run/beamOn 10000

/gun/particle neutron
/gun/energy 0.5 eV
/run/beamOn 10000

/gun/particle neutron
/gun/energy 1 eV
/run/beamOn 10000

/gun/particle neutron
/gun/energy 5 eV
/run/beamOn 10000

/gun/particle neutron
/gun/energy 10 eV
/run/beamOn 10000

/gun/particle neutron
/gun/energy 50 eV
/run/beamOn 10000

/gun/particle neutron
/gun/energy 100 eV
/run/beamOn 10000

/gun/particle neutron
/gun/energy 1 keV
/run/beamOn 10000

/gun/particle neutron
/gun/energy 10 keV
/run/beamOn 10000

/gun/particle neutron
/gun/energy 100 keV
/run/beamOn 10000

/gun/particle neutron
/gun/energy 1 MeV
/run/beamOn 10000

/gun/particle neutron
/gun/energy 10 MeV
/run/beamOn 10000